---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-github-com-kubernetes-kubernetes-
spec:
  pipelineRef:
    name: dracon-github-com-kubernetes-kubernetes
  params:
    - name: repository_url
      value: https://github.com/kubernetes/kubernetes.git
    - name: consumer-elasticsearch-url
      value: http://quickstart-es-http.default.svc:9200
  workspaces:
    - name: source-code-ws
      subPath: source-code
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
