---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -github-com-foo-project
namespace: default

resources:
  - https://github.com/ocurity/dracon//components/base/

components:
  - https://github.com/ocurity/dracon//components/sources/git/
  - https://github.com/ocurity/dracon//components/producers/aggregator/
  - https://github.com/ocurity/dracon//components/producers/python-bandit/
  - https://github.com/ocurity/dracon//components/producers/python-pip-safety/
  - https://github.com/ocurity/dracon//components/producers/golang-gosec/
  - https://github.com/ocurity/dracon//components/producers/golang-nancy/
  - https://github.com/ocurity/dracon//components/producers/terraform-tfsec/
  - https://github.com/ocurity/dracon//components/producers/docker-trivy
  - https://github.com/ocurity/dracon//components/enrichers/aggregator/
  - https://github.com/ocurity/dracon//components/enrichers/deduplication/
  - https://github.com/ocurity/dracon//components/enrichers/policy/
  - https://github.com/ocurity/dracon//components/consumers/elasticsearch/
  - https://github.com/ocurity/dracon//components/components/consumers/jira